services:
  jobmanager:
    image: pyflink:latest
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: pyflink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

# version: "3.9"

# services:
#   jobmanager:
#     build:
#       context: .
#       dockerfile: Dockerfile # Path to your Dockerfile
#     environment:
#       - JOB_MANAGER_RPC_ADDRESS=jobmanager
#     command: ["jobmanager.sh"]
#     ports:
#       - "8081:8081" # Flink Web UI
#     networks:
#       - flink-network

#   taskmanager:
#     build:
#       context: .
#       dockerfile: Dockerfile # Path to your Dockerfile
#     environment:
#       - JOB_MANAGER_RPC_ADDRESS=jobmanager
#     command: ["taskmanager.sh"]
#     depends_on:
#       - jobmanager
#     networks:
#       - flink-network

# networks:
#   flink-network:
#     driver: bridge
